-- Taxonomia del motor, extraida de packages/mock/src/datos-motor.ts.
-- ⛔ Generado por scripts/exportar-taxonomia.mjs. No editar a mano.
alter table public.operacion add column if not exists clave text unique;
alter table public.necesidad add column if not exists clave text unique;
alter table public.actividad add column if not exists clave text unique;

insert into public.operacion (clave,nombre,pregunta,estado) values
('op-maneja-stock','Maneja stock o inventario','¿Maneja stock o inventario propio?','confirmada'),
('op-trabaja-turnos','Trabaja con turnos, citas o reservas','¿Atiende con turnos, citas o reservas?','confirmada'),
('op-atiende-whatsapp','Atiende consultas por WhatsApp','¿Recibe consultas por WhatsApp u otro chat?','confirmada'),
('op-reparte-domicilio','Reparte a domicilio','¿Reparte pedidos a domicilio?','confirmada'),
('op-local-circulacion','Tiene local con circulación de gente','¿Tiene un local físico con circulación de clientes?','confirmada'),
('op-varios-profesionales','Trabaja con varios profesionales o técnicos','¿Trabaja con más de un profesional o técnico?','confirmada'),
('op-catalogo-amplio','Maneja catálogo amplio de productos','¿Maneja una variedad amplia de productos?','confirmada'),
('op-compra-proveedores','Compra a proveedores de forma recurrente','¿Compra mercadería o insumos a proveedores de forma recurrente?','confirmada'),
('op-precios-mueven','Sus precios se mueven según demanda o temporada','¿Sus precios cambian según demanda, temporada o mercado?','confirmada'),
('op-administra-espacios','Administra espacios físicos','¿Administra lugares, salas o mesas que se ocupan y se liberan?','confirmada')
on conflict (clave) do update set nombre=excluded.nombre,pregunta=excluded.pregunta;

insert into public.necesidad (clave,nombre,descripcion,pregunta_confirmacion,estado) values
('nec-fuera-horario','Pierde ventas fuera de horario','Consultas que llegan cuando no hay nadie para responder.','¿Le llegan consultas fuera del horario de atención que hoy quedan sin responder?','confirmada'),
('nec-agenda-desordenada','Agenda desordenada','Turnos, citas o reservas coordinados a mano, con choques y olvidos.','¿Coordina turnos o reservas a mano, por mensajes sueltos?','confirmada'),
('nec-no-sabe-reponer','No sabe qué reponer','Compra por costumbre, sin cruzar lo que realmente se vende.','¿Decide qué comprar más por costumbre que por datos de venta?','confirmada'),
('nec-pierde-mercaderia','Se le pierde mercadería','Diferencias entre lo comprado, lo vendido y lo que queda, sin explicación.','¿Nota diferencias entre lo que compra, lo que vende y lo que queda en stock?','confirmada'),
('nec-reparto-ineficiente','Reparto ineficiente','Rutas armadas por orden de llegada del pedido, no por cercanía.','¿El repartidor arma la ruta a criterio propio, sin optimizarla?','confirmada'),
('nec-no-sabe-que-pasa-en-el-local','No sabe qué pasa en el local','Sin forma de saber cuándo hay más movimiento o dónde se pierden clientes.','¿Tiene forma de saber en qué horarios y zonas del local hay más movimiento?','confirmada'),
('nec-precios-desactualizados','Precios desactualizados frente al mercado','El precio queda fijo mientras la demanda, el stock o la competencia cambian.','¿Hace cuánto no revisa precios frente a la competencia o la rotación real?','confirmada'),
('nec-sin-memoria-del-negocio','No tiene memoria del negocio','Sin historial propio para comparar un día, una semana o un mes con otro.','¿Lleva un registro diario de ventas que le permita comparar períodos?','confirmada'),
('nec-no-cotiza-rapido','Tarda en armar una cotización','Cada cotización se arma desde cero, sin una guía de preguntas.','¿Cada cotización nueva la arma desde cero, sin una guía previa?','confirmada'),
('nec-no-vende-online','No tiene canal de venta online','Todo lo que se vende depende de que el cliente pase por el local.','¿Hoy vende exclusivamente en el local, sin canal online?','confirmada'),
('nec-no-ve-el-mercado','No sabe qué hace la competencia','Decide precios y compras sin mirar qué mueve el mercado.','¿Sigue de cerca lo que hacen sus competidores directos?','confirmada'),
('nec-no-controla-espacios','No controla sus espacios en tiempo real','No sabe, en el momento, qué lugares están libres y cuáles ocupados.','¿Sabe en todo momento qué lugares o espacios están libres y cuáles ocupados?','confirmada'),
('nec-no-coordina-recursos-simultaneos','No coordina recursos entre eventos simultáneos','Personal e insumos repartidos parejo aunque la demanda de cada sala sea distinta.','¿Cuando hay varios eventos o salas al mismo tiempo, reparte personal e insumos a ojo?','confirmada')
on conflict (clave) do update set nombre=excluded.nombre,descripcion=excluded.descripcion,pregunta_confirmacion=excluded.pregunta_confirmacion;

insert into public.actividad (clave,nombre,sinonimos,estado) values
('act-repuestera','Repuestera',array['casa de repuestos', 'repuestos', 'autopartes']::text[],'confirmada'),
('act-restaurante','Restaurante',array['gastronomia', 'resto', 'parrilla', 'bar', 'comida']::text[],'confirmada'),
('act-odontologia','Odontología',array['consultorio odontologico', 'clinica dental', 'dentista', 'odontologa', 'odontologo']::text[],'confirmada'),
('act-peluqueria','Peluquería',array['salon de belleza', 'barberia', 'centro de estetica', 'estilista']::text[],'confirmada'),
('act-hotel','Hotel',array['hospedaje', 'posada', 'hosteria']::text[],'confirmada'),
('act-motel','Motel',array['albergue transitorio', 'hotel por horas']::text[],'confirmada'),
('act-veterinaria','Veterinaria',array['clinica veterinaria', 'veterinario']::text[],'confirmada'),
('act-gomeria','Gomería',array['taller de neumaticos', 'servicio de gomas', 'gomeria y alineacion']::text[],'confirmada'),
('act-criadero-de-pollos','Criadero de pollos',array['granja avicola', 'avicola', 'criadero avicola', 'produccion avicola']::text[],'confirmada'),
('act-farmacia','Farmacia',array['botica', 'drogueria']::text[],'confirmada'),
('act-ferreteria','Ferretería',array['ferreteria industrial']::text[],'confirmada'),
('act-supermercado','Supermercado',array['autoservicio', 'minimarket', 'almacen grande']::text[],'confirmada'),
('act-panaderia','Panadería',array['panificadora']::text[],'confirmada'),
('act-taller-mecanico','Taller mecánico',array['mecanica', 'taller automotor']::text[],'confirmada'),
('act-inmobiliaria','Inmobiliaria',array['agencia inmobiliaria', 'corretaje']::text[],'confirmada'),
('act-distribuidora','Distribuidora',array['mayorista', 'deposito']::text[],'confirmada'),
('act-funeraria','Empresa funeraria',array['funeraria', 'casa velatoria', 'servicio funebre']::text[],'confirmada'),
('act-estacionamiento','Estacionamiento',array['parking', 'playa de estacionamiento', 'garage']::text[],'confirmada'),
('act-boutique','Boutique de ropa',array['tienda de ropa', 'moda', 'indumentaria']::text[],'confirmada'),
('act-electronica','Tienda de electrónica',array['celulares y tecnologia', 'tecnologia']::text[],'confirmada'),
('act-perfumeria','Perfumería',array['cosmetica']::text[],'confirmada'),
('act-vivero','Vivero',array['jardineria', 'plantas']::text[],'confirmada'),
('act-kiosco-de-barrio','Kiosco de barrio',array['despensa', 'almacen de barrio']::text[],'confirmada'),
('act-estudio-de-arquitectura','Estudio de arquitectura',array['estudio de diseno', 'arquitecto', 'arquitecta']::text[],'confirmada'),
('act-concesionaria','Concesionaria de vehículos',array['venta de vehiculos', 'agencia de autos']::text[],'confirmada'),
('act-climatizacion','Climatización',array['aire acondicionado', 'refrigeracion']::text[],'confirmada')
on conflict (clave) do update set nombre=excluded.nombre,sinonimos=excluded.sinonimos;

insert into public.actividad_operacion (actividad_id,operacion_id,probabilidad,motivo)
select a.id,o.id,v.p::probabilidad,v.m from (values
('act-repuestera','op-maneja-stock','tipica','Una repuestera vive de tener la pieza correcta en stock.'),
('act-repuestera','op-catalogo-amplio','tipica','Maneja cientos de referencias distintas por marca y modelo.'),
('act-repuestera','op-compra-proveedores','frecuente','Repone contra proveedores e importadores de forma recurrente.'),
('act-repuestera','op-precios-mueven','ocasional','El precio de importación y el tipo de cambio mueven el costo de reposición.'),
('act-restaurante','op-local-circulacion','tipica','Un restaurante vive de la circulación de comensales en el salón.'),
('act-restaurante','op-trabaja-turnos','frecuente','Las reservas de mesa funcionan como turnos.'),
('act-restaurante','op-reparte-domicilio','frecuente','El delivery es hoy un canal habitual de la gastronomía.'),
('act-restaurante','op-compra-proveedores','frecuente','Compra insumos frescos a proveedores de forma recurrente.'),
('act-odontologia','op-trabaja-turnos','tipica','La atención odontológica se organiza por turno.'),
('act-odontologia','op-varios-profesionales','frecuente','Es frecuente que un consultorio tenga más de un odontólogo.'),
('act-odontologia','op-atiende-whatsapp','frecuente','Las consultas y confirmaciones de turno suelen llegar por WhatsApp.'),
('act-peluqueria','op-trabaja-turnos','tipica','El servicio se agenda por turno.'),
('act-peluqueria','op-varios-profesionales','tipica','Suele haber más de un estilista o profesional trabajando en paralelo.'),
('act-peluqueria','op-atiende-whatsapp','frecuente','Los turnos se piden y confirman mayormente por WhatsApp.'),
('act-hotel','op-administra-espacios','tipica','Un hotel administra habitaciones que se ocupan y se liberan como cualquier espacio.'),
('act-hotel','op-trabaja-turnos','tipica','Check-in y check-out funcionan como turnos con horario.'),
('act-hotel','op-precios-mueven','frecuente','La tarifa cambia según temporada y ocupación.'),
('act-hotel','op-atiende-whatsapp','frecuente','Reservas y consultas llegan por WhatsApp fuera del horario de recepción.'),
('act-motel','op-trabaja-turnos','tipica','La habitación se reserva y se libera por turno, casi siempre por horas.'),
('act-motel','op-precios-mueven','tipica','La tarifa cambia según franja horaria y día de la semana.'),
('act-motel','op-atiende-whatsapp','frecuente','Buena parte de las reservas se coordinan por WhatsApp, a cualquier hora.'),
('act-motel','op-maneja-stock','ocasional','Hay insumos de limpieza y amenities que también se reponen.'),
('act-motel','op-local-circulacion','ocasional','La recepción y las áreas comunes tienen circulación, aunque menor que un comercio.'),
('act-veterinaria','op-trabaja-turnos','tipica','Las consultas se agendan por turno.'),
('act-veterinaria','op-maneja-stock','frecuente','Maneja insumos y medicamentos que hay que reponer.'),
('act-veterinaria','op-atiende-whatsapp','frecuente','Consultas y urgencias suelen llegar primero por WhatsApp.'),
('act-gomeria','op-local-circulacion','tipica','Los clientes esperan en el local mientras se hace el servicio.'),
('act-gomeria','op-maneja-stock','tipica','Mantiene stock de neumáticos y repuestos chicos por medida y marca.'),
('act-gomeria','op-atiende-whatsapp','frecuente','Consulta de precio y disponibilidad de medida suele llegar por WhatsApp.'),
('act-gomeria','op-compra-proveedores','frecuente','Repone stock contra distribuidoras de neumáticos.'),
('act-criadero-de-pollos','op-maneja-stock','tipica','Maneja stock de alimento balanceado, insumos veterinarios y aves en distintas etapas.'),
('act-criadero-de-pollos','op-compra-proveedores','tipica','Compra alimento e insumos a proveedores de forma recurrente y en volumen.'),
('act-criadero-de-pollos','op-precios-mueven','frecuente','El precio del pollo y del alimento balanceado se mueven con el mercado agropecuario.'),
('act-criadero-de-pollos','op-reparte-domicilio','ocasional','Parte de la producción se entrega directamente a comercios o clientes.'),
('act-farmacia','op-maneja-stock','tipica','El medicamento vencido o faltante es un problema central del rubro.'),
('act-farmacia','op-catalogo-amplio','tipica','Maneja cientos de productos entre medicamentos y perfumería.'),
('act-farmacia','op-reparte-domicilio','frecuente','El delivery de medicamentos es un servicio habitual.'),
('act-farmacia','op-atiende-whatsapp','frecuente','Consultas de stock y precio llegan por WhatsApp.'),
('act-ferreteria','op-catalogo-amplio','tipica','Miles de referencias chicas conviven en el mismo local.'),
('act-ferreteria','op-maneja-stock','tipica','La rotación de cada ítem es muy distinta entre sí.'),
('act-ferreteria','op-compra-proveedores','frecuente','Repone contra múltiples proveedores por rubro.'),
('act-supermercado','op-maneja-stock','tipica','El stock es el corazón de la operación diaria.'),
('act-supermercado','op-catalogo-amplio','tipica','Maneja miles de productos de rotación muy distinta.'),
('act-supermercado','op-local-circulacion','tipica','La circulación de clientes en el salón de ventas es constante.'),
('act-supermercado','op-compra-proveedores','frecuente','Repone contra decenas de proveedores.'),
('act-panaderia','op-local-circulacion','tipica','El mostrador tiene circulación constante durante el día.'),
('act-panaderia','op-maneja-stock','frecuente','Maneja insumos de producción que se reponen seguido.'),
('act-taller-mecanico','op-trabaja-turnos','tipica','Los vehículos entran al taller con turno u orden de trabajo.'),
('act-taller-mecanico','op-maneja-stock','frecuente','Maneja stock de repuestos e insumos propios.'),
('act-taller-mecanico','op-atiende-whatsapp','frecuente','Consultas de diagnóstico y presupuesto llegan por WhatsApp.'),
('act-inmobiliaria','op-atiende-whatsapp','tipica','Las consultas por una propiedad llegan sobre todo por WhatsApp.'),
('act-inmobiliaria','op-varios-profesionales','frecuente','Suele trabajar con varios corredores en paralelo.'),
('act-inmobiliaria','op-catalogo-amplio','ocasional','La cartera de propiedades puede ser amplia y variada.'),
('act-distribuidora','op-reparte-domicilio','tipica','Entrega pedidos a comercios de forma habitual.'),
('act-distribuidora','op-maneja-stock','tipica','Su negocio depende de tener stock disponible para despachar.'),
('act-distribuidora','op-compra-proveedores','tipica','Compra en volumen a proveedores o fabricantes.'),
('act-distribuidora','op-catalogo-amplio','frecuente','Distribuye múltiples líneas de producto.'),
('act-funeraria','op-administra-espacios','tipica','Administra salas velatorias que se ocupan y se liberan según el servicio.'),
('act-funeraria','op-varios-profesionales','frecuente','Coordina distintos roles de personal durante cada servicio.'),
('act-funeraria','op-atiende-whatsapp','frecuente','Buena parte de la coordinación con la familia ocurre por WhatsApp.'),
('act-estacionamiento','op-administra-espacios','tipica','Administrar lugares libres y ocupados es la operación completa del negocio.'),
('act-estacionamiento','op-precios-mueven','ocasional','Algunas playas ajustan tarifa por franja horaria.'),
('act-boutique','op-catalogo-amplio','tipica','Maneja variedad de talles, colores y modelos por temporada.'),
('act-boutique','op-local-circulacion','tipica','La prueba de producto ocurre en el local, con circulación de clientas.'),
('act-boutique','op-precios-mueven','frecuente','El precio baja fuerte al cierre de cada temporada.'),
('act-electronica','op-catalogo-amplio','tipica','Maneja múltiples marcas y modelos en simultáneo.'),
('act-electronica','op-maneja-stock','tipica','El stock por modelo determina directamente la venta.'),
('act-electronica','op-precios-mueven','frecuente','Los modelos pierden valor rápido cuando sale una versión nueva.'),
('act-electronica','op-atiende-whatsapp','frecuente','Consultas de precio y stock llegan sobre todo por WhatsApp.'),
('act-perfumeria','op-catalogo-amplio','tipica','Maneja muchas líneas y presentaciones distintas.'),
('act-perfumeria','op-maneja-stock','frecuente','Los productos chicos y caros son los que más se extravían.'),
('act-perfumeria','op-local-circulacion','frecuente','Depende de la circulación y la prueba de producto en el local.'),
('act-vivero','op-maneja-stock','tipica','Las plantas y los insumos de jardinería son stock perecedero.'),
('act-vivero','op-local-circulacion','frecuente','Los clientes recorren el vivero antes de elegir.'),
('act-vivero','op-precios-mueven','ocasional','Algunas especies tienen precio estacional.'),
('act-kiosco-de-barrio','op-maneja-stock','tipica','Vive de tener siempre lo básico disponible.'),
('act-kiosco-de-barrio','op-catalogo-amplio','frecuente','Suele combinar muchos rubros chicos en poco espacio.'),
('act-kiosco-de-barrio','op-atiende-whatsapp','ocasional','Algunos pedidos y encargos llegan por WhatsApp al vecino.'),
('act-estudio-de-arquitectura','op-varios-profesionales','tipica','Suele combinar arquitectos, dibujantes y otros roles técnicos.'),
('act-estudio-de-arquitectura','op-atiende-whatsapp','frecuente','El seguimiento de obra y consultas ocurre mayormente por WhatsApp.'),
('act-estudio-de-arquitectura','op-trabaja-turnos','ocasional','Las reuniones con clientes se agendan como turnos.'),
('act-concesionaria','op-catalogo-amplio','tipica','Maneja varios modelos y versiones en simultáneo.'),
('act-concesionaria','op-varios-profesionales','frecuente','Trabaja con varios vendedores y asesores de crédito.'),
('act-concesionaria','op-atiende-whatsapp','frecuente','Las primeras consultas de precio llegan mayormente por WhatsApp.'),
('act-climatizacion','op-catalogo-amplio','frecuente','Cada ambiente necesita un equipo distinto según metros y uso.'),
('act-climatizacion','op-atiende-whatsapp','frecuente','La primera consulta suele llegar por WhatsApp con una foto del ambiente.'),
('act-climatizacion','op-reparte-domicilio','ocasional','La instalación implica traslado de equipo y técnico.'),
('act-climatizacion','op-varios-profesionales','ocasional','Puede combinar vendedor y técnico instalador.')
) as v(a,o,p,m)
join public.actividad a on a.clave=v.a join public.operacion o on o.clave=v.o
on conflict (actividad_id,operacion_id) do update set probabilidad=excluded.probabilidad,motivo=excluded.motivo;

insert into public.operacion_necesidad (operacion_id,necesidad_id,probabilidad,motivo)
select o.id,n.id,v.p::probabilidad,v.m from (values
('op-atiende-whatsapp','nec-fuera-horario','tipica','Un negocio que atiende por WhatsApp recibe mensajes a cualquier hora, incluida la que nadie contesta.'),
('op-trabaja-turnos','nec-agenda-desordenada','tipica','Coordinar turnos a mano es la primera fuente de choques y olvidos.'),
('op-trabaja-turnos','nec-fuera-horario','frecuente','Los pedidos de turno también llegan fuera de horario, y hoy quedan sin respuesta hasta el día siguiente.'),
('op-maneja-stock','nec-no-sabe-reponer','tipica','Manejar stock sin cruzarlo con lo vendido lleva a comprar por costumbre.'),
('op-maneja-stock','nec-pierde-mercaderia','frecuente','Todo stock físico acumula diferencias entre lo que entra, lo que sale y lo que queda.'),
('op-reparte-domicilio','nec-reparto-ineficiente','tipica','Repartir sin ordenar las paradas multiplica los kilómetros recorridos.'),
('op-local-circulacion','nec-no-sabe-que-pasa-en-el-local','tipica','Con circulación de gente y sin cámaras que se analicen, el movimiento real del local queda sin medir.'),
('op-local-circulacion','nec-sin-memoria-del-negocio','ocasional','Un local con movimiento diario genera datos que, sin registrarlos, se pierden día a día.'),
('op-varios-profesionales','nec-agenda-desordenada','frecuente','Coordinar la agenda de varios profesionales a mano multiplica los choques de horario.'),
('op-catalogo-amplio','nec-no-sabe-reponer','frecuente','Cuanto más amplio el catálogo, más difícil decidir a ojo qué reponer primero.'),
('op-catalogo-amplio','nec-precios-desactualizados','ocasional','Un catálogo amplio es difícil de revisar producto por producto contra el mercado.'),
('op-catalogo-amplio','nec-no-cotiza-rapido','frecuente','Con muchas combinaciones posibles, armar una cotización a medida lleva tiempo sin una guía.'),
('op-catalogo-amplio','nec-no-vende-online','ocasional','Un catálogo amplio que sólo se puede ver en el local limita el alcance del negocio.'),
('op-compra-proveedores','nec-pierde-mercaderia','frecuente','Cada compra a proveedores es un punto donde el conteo puede empezar a desviarse.'),
('op-compra-proveedores','nec-no-ve-el-mercado','ocasional','Comprar a proveedores sin mirar el mercado deja pasar cambios de precio y de oferta.'),
('op-precios-mueven','nec-precios-desactualizados','tipica','Si el precio se mueve por temporada o demanda, un precio fijo queda desactualizado rápido.'),
('op-precios-mueven','nec-no-ve-el-mercado','frecuente','Ajustar precios sin mirar a la competencia es decidir a ciegas.'),
('op-administra-espacios','nec-no-controla-espacios','tipica','Administrar espacios sin verlos en tiempo real es la definición misma de este dolor.'),
('op-administra-espacios','nec-no-coordina-recursos-simultaneos','ocasional','Varios espacios en uso al mismo tiempo exigen repartir recursos, no dividirlos parejo.')
) as v(o,n,p,m)
join public.operacion o on o.clave=v.o join public.necesidad n on n.clave=v.n
on conflict (operacion_id,necesidad_id) do update set probabilidad=excluded.probabilidad,motivo=excluded.motivo;

insert into public.necesidad_producto (necesidad_id,producto_id,encaje,adaptacion_requerida,argumento,motivo)
select n.id,v.pr,v.e::encaje_producto,v.ad,v.ar,v.mo from (values
('nec-fuera-horario','vendedor-24-7','directo',null,'Responde la consulta en el momento en que hoy nadie está disponible.','Es exactamente el problema que resuelve: atender cuando no hay nadie del equipo.'),
('nec-fuera-horario','agendar-ia','cercano','Configurarlo como canal de reserva y no de venta consultiva.','Convierte la consulta de fuera de horario directamente en un turno reservado.','No responde consultas generales, pero puede tomar la reserva en el mismo momento.'),
('nec-fuera-horario','cotiza-facil','adaptable','Cargar previamente precios, condiciones y descuentos permitidos.','Deja una cotización lista para revisar apenas se retoma el horario de atención.','Sirve si ya está cargado con precios y reglas de descuento; si no, no hay nada que mostrar fuera de horario.'),
('nec-agenda-desordenada','agendar-ia','directo',null,'Ordena turnos, profesionales y horarios reales en un solo lugar.','Es su función central: coordinar la agenda de un equipo.'),
('nec-agenda-desordenada','vendedor-24-7','cercano','Conectarlo con el flujo de reservas para que derive, no sólo informe.','Puede derivar la conversación hacia un turno en lugar de dejarla suelta.','Ordena la conversación de venta, no la agenda en sí misma.'),
('nec-no-sabe-reponer','radar-stock','directo',null,'Muestra qué se está por terminar y qué lleva meses sin salida antes de la próxima compra.','Es su función central: decidir con datos qué reponer.'),
('nec-no-sabe-reponer','precio-vivo','cercano',null,'Detecta qué está quedando parado antes de que valga la pena bajarle el precio.','Mira la rotación para decidir precio, no para decidir compra, pero el dato es el mismo.'),
('nec-no-sabe-reponer','merma-ia','adaptable','Usar sus reportes de diferencias como insumo para la próxima compra, no como reemplazo de Radar Stock.','Cruza lo que falta con lo que efectivamente se perdió, no sólo con lo que se vendió.','Su foco es la pérdida, no la reposición; sirve como segunda lectura del mismo problema.'),
('nec-pierde-mercaderia','merma-ia','directo',null,'Compara compras, ventas y stock real para señalar dónde está la diferencia.','Es su función central: encontrar mercadería que se pierde.'),
('nec-pierde-mercaderia','radar-stock','cercano',null,'Al mostrar qué debería quedar en stock, expone las mismas diferencias desde otro ángulo.','Ordena reposición, no pérdidas; el cruce de datos es parecido pero el foco es distinto.'),
('nec-reparto-ineficiente','ruta-ia','directo',null,'Reordena las mismas entregas para recorrer menos kilómetros con el mismo repartidor.','Es su función central: ordenar rutas de reparto.'),
('nec-no-sabe-que-pasa-en-el-local','ojo-digital','directo',null,'Muestra horarios de mayor movimiento y zonas por donde casi nadie pasa.','Es su función central: leer la circulación real del local.'),
('nec-precios-desactualizados','precio-vivo','directo',null,'Sugiere subir, bajar o mantener cada precio según rotación, stock y costo de reposición.','Es su función central: mantener el precio alineado con lo que realmente pasa con cada producto.'),
('nec-precios-desactualizados','faro-digital','cercano',null,'Muestra cómo se mueven los precios de la competencia antes de decidir el propio.','Informa el contexto de mercado; la decisión de precio final la toma Precio Vivo o el dueño.'),
('nec-sin-memoria-del-negocio','pulso-digital','directo',null,'Construye un historial propio del negocio día a día, comparable en el tiempo.','Es su función central: dar memoria al negocio a partir de unos pocos datos diarios.'),
('nec-sin-memoria-del-negocio','merma-ia','adaptable','Combinar sus reportes con un registro diario del negocio, no reemplazarlo.','Suma al historial diario el dato de qué se pierde y cuándo, no sólo qué se vende.','Su historial es de compras, ventas y stock, no de la operación diaria completa.'),
('nec-no-cotiza-rapido','cotiza-facil','directo',null,'Hace primero las preguntas que cambian la recomendación y arma la cotización recién después.','Es su función central: acelerar y ordenar la cotización consultiva.'),
('nec-no-cotiza-rapido','vendedor-24-7','cercano',null,'Adelanta las preguntas del cliente antes de que un vendedor humano retome la conversación.','Prepara el terreno para cotizar, pero no arma la cotización en sí.'),
('nec-no-vende-online','smart-commerce','directo',null,'Abre una tienda online que funciona incluso con el local cerrado.','Es su función central: dar un canal de venta digital propio.'),
('nec-no-vende-online','vendedor-24-7','cercano',null,'Permite mostrar catálogo y precios por WhatsApp mientras no exista una tienda propia.','No es una tienda: es un canal de conversación que puede sostener ventas simples mientras tanto.'),
('nec-no-ve-el-mercado','faro-digital','directo',null,'Sigue precios, promociones y productos nuevos de la competencia visible.','Es su función central: mirar el mercado para que la decisión no sea a ciegas.'),
('nec-no-ve-el-mercado','precio-vivo','cercano',null,'Usa precios de competencia, cuando están disponibles, como un dato más para su sugerencia.','El mercado es un insumo de su cálculo, no su foco principal.'),
('nec-no-controla-espacios','park-ia','directo',null,'Muestra en tiempo real qué lugares están libres, cuáles ocupados, y calcula el cobro de cada uno.','Es su función central: administrar espacios que se ocupan y se liberan.'),
('nec-no-coordina-recursos-simultaneos','exeq-ia','directo',null,'Detecta qué sala está aumentando su ocupación para redistribuir personal e insumos hacia ahí.','Es su función central: coordinar recursos entre servicios simultáneos.')
) as v(n,pr,e,ad,ar,mo)
join public.necesidad n on n.clave=v.n
on conflict (necesidad_id,producto_id) do update set encaje=excluded.encaje,adaptacion_requerida=excluded.adaptacion_requerida,argumento=excluded.argumento,motivo=excluded.motivo;

insert into public.producto (id,nombre,familia,orden,clave_copy,alias_historicos,publicado) values
('ojo-digital','Ojo Digital','especifica'::familia_producto,1,'ojo-digital',array[]::text[],true),
('pulso-digital','Pulso Digital','especifica'::familia_producto,2,'pulso-digital',array[]::text[],true),
('vendedor-24-7','Vendedor 24/7','especifica'::familia_producto,3,'vendedor-24-7',array[]::text[],true),
('radar-stock','Radar Stock','especifica'::familia_producto,4,'radar-stock',array[]::text[],true),
('faro-digital','Faro Digital','especifica'::familia_producto,5,'faro-digital',array['FARO Inteligente']::text[],true),
('merma-ia','Merma IA','especifica'::familia_producto,6,'merma-ia',array[]::text[],true),
('cotiza-facil','Cotiza Fácil','especifica'::familia_producto,7,'cotiza-facil',array[]::text[],true),
('precio-vivo','Precio Vivo','especifica'::familia_producto,8,'precio-vivo',array[]::text[],true),
('ruta-ia','Ruta IA','especifica'::familia_producto,9,'ruta-ia',array[]::text[],true),
('park-ia','Park.IA','integral'::familia_producto,10,'park-ia',array[]::text[],true),
('smart-commerce','Smart Commerce','integral'::familia_producto,11,'smart-commerce',array[]::text[],true),
('agendar-ia','Agendar.IA','integral'::familia_producto,12,'agendar-ia',array[]::text[],true),
('exeq-ia','Exeq.IA','integral'::familia_producto,13,'exeq-ia',array[]::text[],true)
on conflict (id) do update set nombre=excluded.nombre,familia=excluded.familia,orden=excluded.orden,clave_copy=excluded.clave_copy,alias_historicos=excluded.alias_historicos,publicado=excluded.publicado;

delete from public.precio_lista;
insert into public.precio_lista (producto_id,modalidad,plan,estado,moneda,monto_desde,monto_hasta,iva_incluido,texto_documentado,condicion,version_catalogo) values
('ojo-digital','setup'::modalidad_precio,null,'documentado_desde'::estado_precio,'PYG'::moneda,700000,null,null,'desde aproximadamente Gs. 700.000',null,1),
('ojo-digital','mensualidad'::modalidad_precio,null,'documentado_rango'::estado_precio,'PYG'::moneda,350000,1100000,null,'aproximadamente Gs. 350.000 a Gs. 1.100.000',null,1),
('pulso-digital','mensualidad'::modalidad_precio,null,'documentado_rango'::estado_precio,'PYG'::moneda,270000,960000,null,'Gs. 270.000 a Gs. 960.000 por mes, según plan',null,1),
('vendedor-24-7','mensualidad'::modalidad_precio,null,'documentado_rango'::estado_precio,'PYG'::moneda,590000,1500000,null,'Aproximadamente Gs. 590.000 a Gs. 1.500.000 por mes, según cantidad de conversaciones y funciones',null,1),
('radar-stock','mensualidad'::modalidad_precio,null,'documentado_rango'::estado_precio,'PYG'::moneda,270000,900000,null,'Aproximadamente Gs. 270.000 a Gs. 900.000 por mes, según cantidad de productos y plan',null,1),
('faro-digital','mensualidad'::modalidad_precio,null,'documentado_rango'::estado_precio,'PYG'::moneda,108000,630000,null,'Gs. 108.000 a Gs. 630.000 por mes, según alcance',null,1),
('faro-digital','setup'::modalidad_precio,null,'documentado_rango'::estado_precio,'PYG'::moneda,600000,2700000,null,'La implementación observada va desde aproximadamente Gs. 600.000 a Gs. 2.700.000',null,1),
('merma-ia','mensualidad'::modalidad_precio,null,'documentado_desde'::estado_precio,'PYG'::moneda,80000,null,null,'Desde Gs. 80.000 por mes para un rubro. El valor sube si se analizan varios rubros o un alcance mayor',null,1),
('cotiza-facil','prueba'::modalidad_precio,null,'documentado_exacto'::estado_precio,'PYG'::moneda,3900000,null,false,'Prueba de 30 días: Gs. 3.900.000 + IVA',null,1),
('cotiza-facil','setup'::modalidad_precio,null,'documentado_desde'::estado_precio,'PYG'::moneda,4900000,null,false,'Implementación: desde Gs. 4.900.000 + IVA',null,1),
('cotiza-facil','mensualidad'::modalidad_precio,null,'documentado_desde'::estado_precio,'PYG'::moneda,690000,null,false,'Mensual: desde Gs. 690.000 + IVA',null,1),
('cotiza-facil','mensualidad'::modalidad_precio,null,'documentado_desde'::estado_precio,'PYG'::moneda,5900000,null,false,'Planes de mayor alcance llegan a Gs. 5.900.000/mes o más','Planes de mayor alcance',1),
('precio-vivo','setup'::modalidad_precio,null,'documentado_rango'::estado_precio,'USD'::moneda,30000,80000,null,'Implementación: USD 300 a USD 800',null,1),
('precio-vivo','mensualidad'::modalidad_precio,null,'documentado_rango'::estado_precio,'USD'::moneda,15000,40000,null,'Mensual: USD 150 a USD 400',null,1),
('precio-vivo','mensualidad'::modalidad_precio,null,'documentado_desde'::estado_precio,'USD'::moneda,60000,null,null,'Alcances grandes: desde USD 600/mes','Alcances grandes',1),
('ruta-ia','mensualidad'::modalidad_precio,null,'documentado_exacto'::estado_precio,'PYG'::moneda,90000,null,null,'1 repartidor: Gs. 90.000/mes','1 repartidor',1),
('ruta-ia','mensualidad'::modalidad_precio,null,'documentado_exacto'::estado_precio,'PYG'::moneda,180000,null,null,'2 a 4 repartidores: Gs. 180.000/mes','2 a 4 repartidores',1),
('ruta-ia','mensualidad'::modalidad_precio,null,'documentado_exacto'::estado_precio,'PYG'::moneda,320000,null,null,'5 o más: Gs. 320.000/mes','5 o más repartidores',1),
('park-ia','unica_vez'::modalidad_precio,'Piloto Control','documentado_exacto'::estado_precio,'PYG'::moneda,1500000,null,null,'Piloto Control: Gs. 1.500.000 por única vez',null,1),
('park-ia','setup'::modalidad_precio,'Base','documentado_exacto'::estado_precio,'PYG'::moneda,2900000,null,null,'Park.IA Base: instalación Gs. 2.900.000',null,1),
('park-ia','mensualidad'::modalidad_precio,'Base','documentado_exacto'::estado_precio,'PYG'::moneda,490000,null,null,'mensualidad Gs. 490.000',null,1),
('park-ia','setup'::modalidad_precio,'Control','documentado_exacto'::estado_precio,'PYG'::moneda,4900000,null,null,'Park.IA Control: instalación Gs. 4.900.000',null,1),
('park-ia','mensualidad'::modalidad_precio,'Control','documentado_exacto'::estado_precio,'PYG'::moneda,790000,null,null,'mensualidad Gs. 790.000',null,1),
('park-ia','setup'::modalidad_precio,'Control Plus','documentado_exacto'::estado_precio,'PYG'::moneda,7900000,null,null,'Park.IA Control Plus: instalación Gs. 7.900.000',null,1),
('park-ia','mensualidad'::modalidad_precio,'Control Plus','documentado_exacto'::estado_precio,'PYG'::moneda,1290000,null,null,'mensualidad Gs. 1.290.000',null,1),
('smart-commerce','setup'::modalidad_precio,null,'no_documentado'::estado_precio,'PYG'::moneda,null,null,null,'Precio oficial no encontrado. Se cotiza personalizado',null,1),
('agendar-ia','setup'::modalidad_precio,null,'documentado_exacto'::estado_precio,'PYG'::moneda,3000000,null,null,'Implementación: Gs. 3.000.000',null,1),
('agendar-ia','mensualidad'::modalidad_precio,null,'documentado_exacto'::estado_precio,'PYG'::moneda,790000,null,null,'Mensualidad: Gs. 790.000',null,1),
('exeq-ia','setup'::modalidad_precio,null,'no_documentado'::estado_precio,'PYG'::moneda,null,null,null,'Precio oficial no encontrado. Se cotiza personalizado',null,1);
